version: '3.3'
services:
  app:
    build: .
    volumes:
      - .:/home/work
    ports:
      - 8888:8888
      - 6006:6006
  
  go:
    image: golang
    volumes:
      - .:/usr/src/myapp
    tty: true